xy_goal_tolerance: 0.3194
yaw_goal_tolerance: 1.5
max_obstacle_height: 0.60  # assume something like an arm is mounted on top of the robot
obstacle_range: 10 # added 20180111 #sets maximum range to add new obstacles to cost map
# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
robot_radius: 0.20  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular

obstacle_layer:
  enabled:              true
  track_unknown_space:  true
  publish_voxel_map:    false
  obstacle_range:       5.0
  raytrace_range:       1.0
  max_obstacle_height:  0.6
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             2
  unknown_threshold:    15    
  mark_threshold:       0
  combination_method:   1
  observation_sources: april goal 
  april:
    # sensor_frame: /map
    data_type:    PointCloud2
    # topic:        /hast/april/PointCloud2
    marking:      true
    clearing:     true
  goal:
    # sensor_frame: /map
    data_type:    PointCloud2
    # topic:        /hast/goal/PointCloud2
    marking:      false
    clearing:     true

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     1.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true


