local_costmap:
   # global_frame:      /hast/kobuki/odom
   # robot_base_frame:  /hast/kobuki/base_footprint
   update_frequency:  5.0
   publish_frequency: 2.0
   static_map:        false
   rolling_window:    true
   width:             8.0
   height:            8.0
   resolution:        0.05
   transform_tolerance: 0.5
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

# The origin for the sensor at (0.00, 0.00, 0.00) is out of map bounds. So, the costmap cannot raytrace for it.
