robot_radius: 0.20  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)

obstacle_layer:
  enabled:             true
  observation_sources: april
  april:
    sensor_frame: /map
    data_type:    PointCloud2
    topic:        /hast/april/PointCloud2
    marking:      true
    clearing:     true

inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true

